Add Nextflow icon to badgen
badgen/badgen-icons pull request #60
Opened 2023-09-18 13:08 UTC by mribeirodantas

2023-09-19 14:46 UTC, mribeirodantas commented
@walpox can you merge this, please? 🙂

2023-09-20 12:07 UTC, walpox commented
> @walpox can you merge this, please? 🙂

Hello,
I am afraid I cannot help you as I am a regular contributor without the required permissions to merge your changes.

2023-09-20 13:05 UTC, mribeirodantas commented
Do you know who I should mention to get it merged? 😬

2024-01-07 13:46 UTC, mribeirodantas commented
@amio ? 😅

2024-01-16 19:24 UTC, styfle requested changes
The green fill needs to be removed. See the other icons for an example.

https://badgen-icons-git-fork-mribeirodantas-add-nxf-icon-badgen.vercel.app/

<img width="833" alt="image" src="https://github.com/badgen/badgen-icons/assets/229881/49cbdd03-8e50-4ed5-97ad-6dbb6972db53">

2024-01-16 23:30 UTC, mribeirodantas commented
Thanks for replying, @styfle. It's done now.

2024-01-17 22:03 UTC, styfle commented on icons/nextflow.svg
> +   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
Lets remove all the inkscape specific code

2024-01-18 14:35 UTC, mribeirodantas commented
Done, @styfle. Thanks again 😉

2024-01-18 14:52 UTC, styfle commented on icons/nextflow.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="251" height="251" fill="none"><path fill="#0DC09D" d="M0 47.02c39.45 2.62 71.06 34.307 73.54 73.795h46.07C117.05 55.859 64.93 3.642 0 .943V47.02ZM73.8 1
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="251" height="251"><path fill="#0DC09D" d="M0 47.02c39.45 2.62 71.06 34.307 73.54 73.795h46.07C117.05 55.859 64.93 3.642 0 .943V47.02ZM73.8 131.324c-2.62 39.447-34.31 71.055-73.8 73.535v46.067c64.96-2.56 117.18-54.677 119.88-119.602H73.8ZM176.201 120.545c2.62-39.448 34.31-71.056 73.8-73.535V.943c-64.96 2.56-117.18 54.676-119.88 119.602h46.08ZM250.001 204.849c-39.45-2.62-71.06-34.307-73.54-73.795h-46.07c2.56 64.956 54.68 117.172 119.61 119.872v-46.077Z"/></svg>
```

2024-01-18 14:53 UTC, styfle commented on icons/nextflow.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="251" height="251"><path fill="#0DC09D" d="M0 47.02c39.45 2.62 71.06 34.307 73.54 73.795h46.07C117.05 55.859 64.93 3.642 0 .943V47.02ZM73.8 131.324c-2.62
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="251" height="251"><path fill="#fff" d="M0 47.02c39.45 2.62 71.06 34.307 73.54 73.795h46.07C117.05 55.859 64.93 3.642 0 .943V47.02ZM73.8 131.324c-2.62 39.447-34.31 71.055-73.8 73.535v46.067c64.96-2.56 117.18-54.677 119.88-119.602H73.8ZM176.201 120.545c2.62-39.448 34.31-71.056 73.8-73.535V.943c-64.96 2.56-117.18 54.676-119.88 119.602h46.08ZM250.001 204.849c-39.45-2.62-71.06-34.307-73.54-73.795h-46.07c2.56 64.956 54.68 117.172 119.61 119.872v-46.077Z"/></svg>
```

2024-01-18 14:54 UTC, styfle approved these changes
I pushed a few more changes, thanks!

2024-01-18 14:54 UTC, merged

2024-01-18 16:51 UTC, mribeirodantas commented
Does it take a while for the website to be able to render? The icon is not appearing here yet: https://badgen.net/badge/Nextflow/23.10.1/green?icon=nextflow

2024-01-18 20:08 UTC, styfle commented
It deployed here: https://icons.badgen.net

The root badgen.net is a separate repo here: https://github.com/badgen/badgen

2024-01-18 23:04 UTC, mribeirodantas commented
Can you help me with instructions on how I can make the nextflow icon be found in badgen.net, just like the GitHub one?

2024-02-18 07:28 UTC, amio commented
Thanks @mribeirodantas @styfle 

> Can you help me with instructions on how I can make the nextflow icon be found in badgen.net, just like the GitHub one?

Currently we need to release a new version of this npm package, then update the dependency in badgen.net.
I think we better migrate this repo into https://github.com/badgen/badgen.net, to prevent more confusions in future.